### ISSUE TITLE
Mouse cursor incorrectly tracked after changing screen resolution

### ISSUE THREAD

**Issue by gluser2** [virtexedge/metric-racer-sdk#15]
In Metric Racer alpha 0.7.3.3, going fullscreen at a resolution less than the current size of the display will incorrectly offset the mouse cursor relative to the onscreen buttons. Notice the actual position of the white cursor, versus where the highlighted button thinks it is:
![metricracer-displacedmousecursor](https://user-images.githubusercontent.com/39076497/105644804-2e7f5b80-5e5d-11eb-8c84-6ea8e3ed984d.jpg)

I have also taken a video of the bug here:
https://www.youtube.com/watch?v=wyascZBFBxg

Steps to reproduce:
1. On a 1920x1080 screen (or probably other screen sizes), select a windowed resolution that is smaller than your screen, i.e. 1600x900.
2. Click OK. (Apply does nothing.)
3. Go back into Settings>Graphics.
4. Confirm that 1600x900 is still displayed in Graphics, and change Windowed to Full Screen.
5. Click OK.
6. The screen will be refreshed and now the mouse cursor is offset from where the game thinks it is.

Using Windows 10 64-bit, video recorded with Xbox Game Bar.

**Comment by virtexedge** [comment]
Interesting, that's not the way it should work lol. 
I will take a look, there looks to be a strange offset issue.

**Comment by virtexedge** [comment]
@gluser2 **version 0.7.4.1** was just pushed which fixes this issue. 

Thanks for all of your feedback, I will update the other tickets as I get through them!
