### ISSUE TITLE
Respawn button not always a playable position

### ISSUE THREAD

**Issue by darkgriffin1986** [virtexedge/metric-racer-sdk#17]
When holding respawn to recenter on track, often the spawned position is unplayable.

Examples include spawning on the walls of the track(with alignment to the wall instead of the floor), spawning outside track geometry entirely such as mid air, and spawning right side up on the up side down part of a track.  Tested mainly on the current 4 career tracks.  It seems related to the twisted parts of the track but I can also respawn on the off road sections and get some pretty unplayable spawns on Mars too.  I've also seen the AI get stuck in a loop at these spawns, though they seem to be better at reacting to the strange orientation.

Respawning also seems to maintain the current acceleration and momentum, which might have a lot to do with it not working right.

Ideally, I would like respawn to give me something playable, at either the intended speed of the track section or if at full speed, in the direction of the track (with proper orientation/momentum).

**Comment by virtexedge** [comment]
I think you're right, the momentum must be throwing it off when respawning. Taking a look.

**Comment by virtexedge** [comment]
Hi @darkgriffin1986 , **version 0.7.4.1** has a fixes respawning on track so that the racer appears at a suitable place without any excess momentum.
