### ISSUE TITLE
Walls/rails for campaign or other tracks can act like "floor", getting the ship stuck to it.

### ISSUE THREAD

**Issue by darkgriffin1986** [virtexedge/metric-racer-sdk#18]
The walls/rails sometimes behave like a "floor" if approached or clipped onto wrong.  Can be recreated in the first campaign track New New York pretty easily by simply scraping the outside of the twisted turn at full speed.  When this happens the "ship" thinks the "wall" is a "floor", turning 90 degrees to the left/right and making it nearly impossible to get back onto the proper track lane.

I would greatly prefer if the walls/rails just pretended to be "taller" and vertical, instead of being drivable.  It's just frustrating, the camera isn't designed for that kind of maneuvering, and I don't think user track designs will suffer much if the track sides act more like barriers and less like platforms. :)

**Comment by virtexedge** [comment]
My next priority is to get this sorted out. Right now the floor and rails are being handled as a single mesh. I'll need to split them apart in to separate physics meshes so that the player doesn't end up sideways like that.

**Comment by virtexedge** [comment]
Hi @darkgriffin1986 I've just pushed version 0.7.4.1 which fixes ships getting stuck to the wall as if it's a floor. I did a hefty re-write of the physics mesh handling, so it should be a lot more versatile now. It's also substantially more difficult for racers to get stuck on/in the sides as well.
