### ISSUE TITLE
Flow break when user cancels after selecting Exit Race in Post Race screen

### ISSUE THREAD

**Issue by Fanglespangle** [virtexedge/metric-racer-sdk#29]
Upon finishing a Single Race or a Time Trial, the player is able to select to Restart or Exit the race. If the user selects Exit, but then cancels that, the menu flow breaks and the following happens:

- The user is unable to see the post-race scores (lap times, positions etc)
- The user can not elect to restart the race. Doing so will cause nothing to happen.
- The user can only select to exit the race.

**STEPS TO REPRODUCE**

1. Finish a race or Time Trial and select exit from the Post-Mission screen.
2. Select Cancel.
3. Observe the Post-Race screen doesn't appear and the user cannot elect to restart the race.

Video: 

https://user-images.githubusercontent.com/78652640/107160214-ca948100-698c-11eb-81fd-71aad92e42db.mp4

**Comment by virtexedge** [comment]
I'm tempted to actually leave this as it lets the player watch their racer zoom around the track with no UI obstructing the way. It's a nice background mode.

**Comment by Fanglespangle** [comment]
I agree it's a cool feature, but I would still correct the menu so it properly reflects what it's doing. As it stands, players would only find this if they cancel the exit race menu, which implies they were attempting to do something else. Players who would want to access this feature have no natural way of finding it.

**Comment by virtexedge** [comment]
This has been addressed in Experimental build **0.8.4.210**. The back button has been disabled now for standings dialogs.
