### ISSUE TITLE
Post Race screen in Single Race has a statistic that is not labelled.

### ISSUE THREAD

**Issue by Fanglespangle** [virtexedge/metric-racer-sdk#31]
There is a statistic when a user completes a Single Race that has no label above it. It shows the Racers, their Total Time, Best Time (should this be Fastest Lap?) and a mystery third statistic.

**STEPS TO REPRODUCE**
1. Complete any Single Race
2. Observe in the post Race screen there is a Fourth Column with no Label.

Screenshot included:
![Mystery statistic](https://user-images.githubusercontent.com/78652640/107161162-bce1fa00-6992-11eb-820f-9fcb8ae937db.jpg)

**Comment by virtexedge** [comment]
This should be fixed in v. 0.8 release.
