### ISSUE TITLE
Time Trial only has three laps, yet the Post Race screen shows 10 laps.

### ISSUE THREAD

**Issue by Fanglespangle** [virtexedge/metric-racer-sdk#32]
The Time Trial Post Race screen shows data for 10 laps, but the racer can only complete three laps. There is no option for the player to complete more than 3.

**STEPS TO REPRODUCE**
1. Complete a Time Trial
2. Observe the Post Race screen shows 10 slots for lap times but only 3 are used.

Screenshot: 
![Time Trial lap data](https://user-images.githubusercontent.com/78652640/107161313-df284780-6993-11eb-9983-3359f76e3a59.jpg)

**Comment by virtexedge** [comment]
This is fixed in **v 0.8**.
