### ISSUE TITLE
Sandbox Mode - The Terrain Editor can spawn multiple times which can cause selecting Tools to crash the game.

### ISSUE THREAD

**Issue by Fanglespangle** [virtexedge/metric-racer-sdk#33]
The Edit Terrain tab can be generated multiple times which does not appear to be intended.

If the user activates Terrain Editor from the Entities menu, places any asset from the entities menu and then activates Terrain Editor from the Entities menu again, a second Edit Terrain Tab will appear.

These do not function independently. If the user closes one of these Edit Terrain Tabs, the feature will cease to function. Attempting to close it will not work.

If the User then selects Tools after attempting to close the window, the game will crash.

There are more ways to trigger the crash, but they all stem from this issue.

Video and Log included.

**STEPS TO REPRODUCE**
1. Select Sandbox > New and wait for it to load.
2. Select Entities then select Terrain Editor.
3. Once the green tab appears, click Entities then New Entity and place any Entity into the editor
4. Click Entities > Terrain Editor and observe a second Edit Terrain Tab appears.
5. Attempt to close both of the Edit Terrain Tabs and observe 1 will be left that cannot be removed.
6. Click the Tools tab and observe the game will crash.

Log: 
[metricracer-2021-02-07--22-51-37.txt](https://github.com/virtexedge/metric-racer-sdk/files/5940239/metricracer-2021-02-07--22-51-37.txt)

I added 2 entities in the video, only one needs to be added. This was before I condensed the steps down enough to realise that.
Video: 

https://user-images.githubusercontent.com/78652640/107161862-67f4b280-6997-11eb-80b2-5bd7143198f2.mp4

**Comment by virtexedge** [comment]
This should be fixed in v 0.8 in the sense that it avoids a crash, but it may break the user flow under some circumstances.
