### ISSUE TITLE
[Linux] Crash on launch: libsteam_api64.so

### ISSUE THREAD

**Issue by tdis8629** [virtexedge/metric-racer-sdk#46]
Posted in the [Steam Discussions](https://steamcommunity.com/app/938200/discussions/0/3171072251338579558), but it may be more appropriate here.

In a nutshell, libsteam_api64.so is not properly loaded, as it's looking for it in MetricRacer/lib/steam/. Temporary fix is to create ./lib/steam, then move it there.

**Comment by virtexedge** [comment]
Thanks for the headsup on this, I just pushed a fix in **v0.8.2.46** which is live now

**Comment by tdis8629** [comment]
Can confirm it's updated.
