### ISSUE TITLE
Crashes entering and exiting tracks. 

### ISSUE THREAD

**Issue by RykeWollf** [virtexedge/metric-racer-sdk#62]
I've been getting consistent crashes loading into one of the maps and then another while finishing a race. Unable to determine cause of crash but the crash entering the track seems easy to replicate. 

Crash logs added. 

[metricracer-log-2021-07-08--12-12-57-crash-0.txt](https://github.com/virtexedge/metric-racer-sdk/files/6784141/metricracer-log-2021-07-08--12-12-57-crash-0.txt)
[metricracer-log-2021-07-08--12-13-51-crash-0.txt](https://github.com/virtexedge/metric-racer-sdk/files/6784142/metricracer-log-2021-07-08--12-13-51-crash-0.txt)
[metricracer-log-2021-07-08--12-21-14-crash-0.txt](https://github.com/virtexedge/metric-racer-sdk/files/6784143/metricracer-log-2021-07-08--12-21-14-crash-0.txt)
[metricracer-log-2021-07-08--12-37-02-crash-0.txt](https://github.com/virtexedge/metric-racer-sdk/files/6784144/metricracer-log-2021-07-08--12-37-02-crash-0.txt)

**Comment by RykeWollf** [comment]
Island Station Gamma still crashes upon start after verifying integrity of game files
Attaching MSinfo and DXdiag 

[metricracer-log-2021-07-08--17-22-57-crash-0.txt](https://github.com/virtexedge/metric-racer-sdk/files/6785990/metricracer-log-2021-07-08--17-22-57-crash-0.txt)
[DxDiag.txt](https://github.com/virtexedge/metric-racer-sdk/files/6786008/DxDiag.txt)
[msinfo.txt](https://github.com/virtexedge/metric-racer-sdk/files/6786009/msinfo.txt)

**Comment by RykeWollf** [comment]
Even after the most recent update and verifying files, the game is still crashing when entering island station gamma. Really an odd one, here's the log. 

[metricracer-log-2021-07-13--18-19-46-crash-0.txt](https://github.com/virtexedge/metric-racer-sdk/files/6810805/metricracer-log-2021-07-13--18-19-46-crash-0.txt)

**Comment by virtexedge** [comment]
I'm going to close this issue. Resolved in **0.8.4.177**
