### ISSUE TITLE
Crashes in track editor mode. 

### ISSUE THREAD

**Issue by RykeWollf** [virtexedge/metric-racer-sdk#65]
Hi there, it seems I'm having some crashes when performing certain actions (mostly undo several times) where the game just crashes in track editor. 

Any idea what can be the cause of the issue here? 

EDIT: corrected logs 

[metricracer-log-2021-07-13--10-38-20-crash-0.txt](https://github.com/virtexedge/metric-racer-sdk/files/6809668/metricracer-log-2021-07-13--10-38-20-crash-0.txt)
[metricracer-log-2021-07-13--10-41-39-crash-0.txt](https://github.com/virtexedge/metric-racer-sdk/files/6809669/metricracer-log-2021-07-13--10-41-39-crash-0.txt)
[metricracer-log-2021-07-13--12-08-36-crash-0.txt](https://github.com/virtexedge/metric-racer-sdk/files/6809670/metricracer-log-2021-07-13--12-08-36-crash-0.txt)
[metricracer-log-2021-07-13--12-25-30-crash-0.txt](https://github.com/virtexedge/metric-racer-sdk/files/6809671/metricracer-log-2021-07-13--12-25-30-crash-0.txt)
[metricracer-log-2021-07-13--14-19-56-crash-0.txt](https://github.com/virtexedge/metric-racer-sdk/files/6809672/metricracer-log-2021-07-13--14-19-56-crash-0.txt)

**Comment by virtexedge** [comment]
I'm going to close this issue. Resolved in **0.8.4.177**
